kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector: #labels used as selectors
    app: backend
    tier: backend
    project: expense
  ports:
    - protocol: TCP #port details
      port: 8080
      targetPort: 8080